# Generated by Django 5.0.6 on 2024-07-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('apellido_cli', models.CharField(max_length=50)),
                ('correo_cli', models.EmailField(max_length=254)),
                ('contraseña_cli', models.CharField(max_length=50)),
            ],
        ),
    ]
