# Generated by Django 5.0.6 on 2024-07-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=50)),
                ('precio_prod', models.IntegerField()),
                ('idioma_prod', models.CharField(max_length=25)),
            ],
        ),
    ]
