# Generated by Django 5.0.6 on 2024-07-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=100),
        ),
    ]
